FROM public.ecr.aws/lambda/python:3.10

RUN yum install -y hdf5-devel gcc gcc-c++ pkgconfig && yum clean all

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . ${LAMBDA_TASK_ROOT}

CMD ["main.handler"]
